# Generated by Django 6.0 on 2026-09-19 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinician_overview', '0006_client_unique_client_per_clinician'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoloResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stress_before_elements', models.IntegerField()),
                ('stress_after_elements', models.IntegerField()),
                ('step_2', models.IntegerField()),
                ('step_5pod1_first', models.IntegerField()),
                ('step_5pod1_last', models.IntegerField()),
                ('step_5pod2_first', models.IntegerField()),
                ('step_5pod2_last', models.IntegerField()),
                ('step_5pod3_first', models.IntegerField()),
                ('step_5pod3_last', models.IntegerField()),
                ('step_6', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinician_overview.client')),
            ],
            options={
                'indexes': [models.Index(fields=['client'], name='step_solo_s_client__f5a40c_idx')],
            },
        ),
    ]
