# Generated by Django 5.2.7 on 2026-02-03 02:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('signup_news', models.BooleanField(default=False)),
                ('scoring_email', models.EmailField(max_length=254)),
                ('phone_country', models.CharField(max_length=6)),
                ('phone_number', models.CharField(max_length=20)),
                ('profession', models.CharField(max_length=50)),
                ('profession_other', models.CharField(blank=True, max_length=250)),
                ('practice_years', models.CharField(max_length=50)),
                ('emdr', models.CharField(max_length=50)),
                ('emdr_other', models.CharField(blank=True, max_length=250)),
                ('practice_setting', models.JSONField(verbose_name='')),
                ('practice_other', models.TextField(blank=True)),
                ('client_population', models.JSONField(verbose_name='')),
                ('client_population_other', models.TextField(blank=True)),
                ('access_type', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
