from django.urls import URLPattern, URLResolver, path
import step_solo.views as views


urlpatterns: list[URLPattern | URLResolver] = [
    path('', views.index, name='solo_index'),
    path('what-to-expect', views.what_to_expect, name='solo_what_to_expect'),
    path('self-regulation-strategies', views.self_regulation_strategies, name='solo_self_regulation_strategies'),
    path('introduction', views.step_solo_introduction, name='solo_introduction'),
    path('getting_started', views.getting_started, name='solo_getting_started'),
    path('bilateral_tapping', views.bilateral_tapping, name='solo_bilateral_tapping'),
    path('pre_check_in', views.pre_check_in, name='solo_pre_check_in'),
    path('4_elements', views.four_elements, name='solo_four_elements'),
    path('stress_before_4_elements', views.stress_before_four_elements, name='solo_stress_before_four_elements'),
    path('stress_after_4_elements', views.stress_after_four_elements, name='solo_stress_after_four_elements'),
    path('solo-1', views.solo_1, name="solo_1"),
    path('drawing_guide', views.drawing_guide, name='solo_drawing_guide'),
    path('solo-2', views.solo_2, name='solo_2'),
    path('solo-3', views.solo_n(3), name='solo_3'),
    path('solo-4', views.solo_n(4), name='solo_4'),
    path('solo-5', views.solo_n(5), name='solo_5'),
    path('solo-6', views.solo_n(6), name='solo_6'),
    path('solo-7', views.solo_n(7), name='solo_7'),
    path('solo-8p1', views.solo_8p1, name='solo_8p1'),
    path('solo-8p2', views.solo_8p2, name='solo_8p2'),
    path('solo-9', views.solo_n(9), name='solo_9'),
    path('solo-10', views.solo_n(10), name='solo_10'),
    path('solo-11', views.solo_n(11), name='solo_11'),
    path('solo-12', views.solo_12, name='solo_12'),
    path('sheet-review', views.sheet_review, name='solo_sheet_review'),
    path('step-2', views.step_2, name='solo_step_2'),
    path('step-5pod1', views.step_5_pod_1, name='solo_step_5_pod_1'),
    path('step-5pod1-form', views.step_5_pod_1_form, name='solo_step_5_pod_1_form'),
    path('step-5pod1-last-form', views.step_5_pod_1_last_form, name='solo_step_5_pod_1_last_form'),
    path('step-5pod2', views.step_5_pod_2, name='solo_step_5_pod_2'),
    path('step-5pod2-form', views.step_5_pod_2_form, name='solo_step_5_pod_2_form'),
    path('step-5pod2-last-form', views.step_5_pod_2_last_form, name='solo_step_5_pod_2_last_form'),
    path('step-5pod3', views.step_5_pod_3, name='solo_step_5_pod_3'),
    path('step-5pod3-form', views.step_5_pod_3_form, name='solo_step_5_pod_3_form'),
    path('step-5pod3-last-form', views.step_5_pod_3_last_form, name='solo_step_5_pod_3_last_form'),
    path('step-6', views.step_6, name='solo_step_6'),
    path('step-6-form', views.step_6_form, name='solo_step_6_form'),
    path('worksheet-upload', views.worksheet_upload, name='solo_worksheet_upload'),
    path('container', views.container, name='solo_container'),
    path('four-elements-after', views.four_elements_after, name='solo_four_elements_after'),
    path('complete', views.complete, name='solo_complete'),
]

NUM_SOLO_VIDS = len(urlpatterns) - 1  # exclude the inbdex page