# Generated by Django 5.2.11 on 2026-04-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinician_overview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientid',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
