# Generated by Django 6.0 on 2026-05-13 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinician_overview', '0002_clientid_tags'),
        ('initial_screening', '0002_alter_questionnaireresponse_user_identifier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClientId',
            new_name='Client',
        ),
        migrations.CreateModel(
            name='AccessGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('granted_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinician_overview.client')),
                ('clinician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['clinician', 'client'], name='clinician_o_clinici_bdd22e_idx'), models.Index(fields=['clinician', 'client', 'granted_at'], name='clinician_o_clinici_fb199d_idx'), models.Index(fields=['clinician', 'client', 'revoked_at'], name='clinician_o_clinici_798a23_idx'), models.Index(fields=['clinician', 'client', 'expires_at'], name='clinician_o_clinici_368ffc_idx')],
            },
        ),
    ]
