# Generated by Django 6.0 on 2026-05-16 20:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinician_overview', '0003_rename_clientid_client_accessgrant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessgrant',
            name='granted_at',
            field=models.DateTimeField(auto_now_add=True),
        )
    ]
