# Generated by Django 6.0 on 2026-05-16 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinician_overview', '0004_alter_accessgrant_granted_at_and_more'),
    ]

    operations = [
    ]
