# Generated by Django 6.0 on 2026-05-24 20:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinician_overview', '0005_remove_client_unique_client_per_clinician'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('client_id', 'clinician'), name='unique_client_per_clinician'),
        ),
    ]
