# Generated by Django 5.2.11 on 2026-07-01 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_version_date', models.DateTimeField(auto_now_add=True)),
                ('text_questions', models.JSONField()),
                ('confirmation_questions', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='ProviderAgrees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=100)),
                ('provider_organization', models.CharField(max_length=100)),
                ('agreement_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
