# Generated by Django 5.2.11 on 2026-07-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step_together', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='current',
            field=models.BooleanField(default=True),
        ),
    ]
