# Generated by Django 5.2.11 on 2026-07-03 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step_together', '0002_agreement_current'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgreementCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_text', models.TextField()),
                ('confirmation_checkbox_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProviderConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=100)),
                ('provider_organization', models.CharField(max_length=100)),
                ('agreement_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TextQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='ProviderAgrees',
        ),
        migrations.RemoveField(
            model_name='agreement',
            name='confirmation_questions',
        ),
        migrations.RemoveField(
            model_name='agreement',
            name='text_questions',
        ),
        migrations.AddField(
            model_name='agreementcondition',
            name='agreement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='step_together.agreement'),
        ),
        migrations.AddField(
            model_name='providerconfirmation',
            name='agreement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='step_together.agreement'),
        ),
        migrations.AddField(
            model_name='textquestion',
            name='agreement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='step_together.agreement'),
        ),
    ]
