# Generated by Django 5.2.11 on 2026-05-10 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinician_overview', '0002_clientid_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
                ('citation', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveBigIntegerField(default=0)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initial_screening.form')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initial_screening.questionnaire')),
            ],
            options={
                'unique_together': {('questionnaire', 'form')},
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000)),
                ('question_type', models.CharField(choices=[('info', 'Informational Block'), ('text', 'Single Line Text'), ('textarea', 'Long Text'), ('radio', 'Multiple Choice (Single-select)'), ('checkbox', 'Multiple Choice (Multi-select)'), ('dropdown', 'Dropdown'), ('date', 'Date')], default='text', max_length=30)),
                ('order', models.PositiveBigIntegerField(default=0)),
                ('is_required', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('order', models.PositiveBigIntegerField(default=0)),
                ('internal_value', models.CharField(max_length=255, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='initial_screening.question')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='question_block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='initial_screening.questionblock'),
        ),
        migrations.AddField(
            model_name='questionblock',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_blocks', to='initial_screening.questionnaire'),
        ),
        migrations.CreateModel(
            name='QuestionnaireResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('view_count', models.IntegerField(default=0)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initial_screening.form')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initial_screening.questionnaire')),
                ('user_identifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinician_overview.clientid')),
            ],
        ),
        migrations.CreateModel(
            name='ResponseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('answerID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='initial_screening.answeroption')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initial_screening.question')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='initial_screening.questionnaireresponse')),
            ],
        )
    ]
