# Generated by Django 6.0 on 2026-05-12 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinician_overview', '0002_clientid_tags'),
        ('initial_screening', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='user_identifier',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='clinician_overview.clientid'),
            preserve_default=False,
        ),
    ]
