# Generated by Django 5.2.11 on 2026-06-28 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initial_screening', '0002_alter_questionnaireresponse_user_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='omit_notifications',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
