# Generated by Django 5.2.11 on 2026-06-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initial_screening', '0003_questionnaire_omit_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
