# Generated by Django 5.2.11 on 2026-06-28 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initial_screening', '0004_form_anonymous'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='anonymous',
        ),
    ]
