# Generated by Django 5.2.11 on 2026-06-29 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initial_screening', '0005_remove_form_anonymous'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
