# Generated by Django 5.2.11 on 2026-06-29 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinician_overview', '0006_client_unique_client_per_clinician'),
        ('initial_screening', '0007_alter_questionnaireresponse_questionnaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initial_screening.questionnaire'),
        ),
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='user_identifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinician_overview.client'),
        ),
    ]
