# Generated by Django 5.2.11 on 2026-07-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initial_screening', '0008_alter_questionnaireresponse_questionnaire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='anonymous',
            field=models.BooleanField(default=False, help_text='If the form is anonymous, STEP will not display user answers to the clinician. There is no enforcement as to whether a question collecting user identity has been added.'),
        ),
        migrations.AlterField(
            model_name='form',
            name='name',
            field=models.CharField(help_text='The name of the form. This is for internal use only and will not be shown to the user.', max_length=300, unique=True),
        ),
    ]
