# Generated by Django 5.2.11 on 2026-08-05 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initial_screening', '0010_question_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='image',
        ),
        migrations.AddField(
            model_name='question',
            name='image_url',
            field=models.TextField(blank=True, help_text='Optional URL for an image to display with the question.', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('info', 'Informational Block'), ('text', 'Single Line Text'), ('textarea', 'Long Text'), ('radio', 'Multiple Choice (Single-select)'), ('checkbox', 'Multiple Choice (Multi-select)'), ('dropdown', 'Dropdown'), ('date', 'Date'), ('file', 'File')], default='text', max_length=30),
        ),
    ]
