# Generated by Django 5.2.11 on 2026-08-05 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initial_screening', '0011_remove_question_image_question_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='hide_title',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
