# Generated by Django 6.0 on 2026-08-14 04:59

import initial_screening.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initial_screening', '0012_questionnaire_hide_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='responseitem',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=initial_screening.models.document_upload_path),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.CheckConstraint(condition=models.Q(('text__isnull', False), ('image_url__isnull', False), _connector='OR'), name='not_both_image_and_question_text_null'),
        ),
    ]
