# Generated by Django 6.0 on 2026-08-15 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initial_screening', '0013_responseitem_file_alter_question_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answeroption',
            name='internal_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
